name: CI Workflow

on: push

jobs:
   eslint:
      if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v2.1.1

         - name: Setup Node.js environment
           uses: actions/setup-node@v1.4.2
           with:
              node-version: 14.x

         - name: Cache node modules
           id: node-modules
           uses: actions/cache@v2
           with:
              path: node_modules
              key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
              restore-keys: |
                 ${{ runner.os }}-node-

         - if: steps.node-modules.outputs.cache-hit != 'true'
           run: npm i

         - name: eslint / tslint
           run: npm run lint
